parameters:
#    thread_and_mirror_alert.example.class: ThreadAndMirror\AlertBundle\Example

services:
#    thread_and_mirror_alert.example:
#        class: %thread_and_mirror_alert.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
