imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        site_url: %stems.site.url%
        stems_theme: %stems.site.theme%
        stems_site_name:  %stems.site.name%
        stems_site_keywords: %stems.site.keywords%
        stems_site_description: %stems.site.description%
        service_stems_section: '@stems.core.sections.manager'

# Elastic Search
fos_elastica:
    clients:
        default: { host: 127.0.0.1, port: 9200 }
    indexes:
        search:
            client: default
            types:
                product:
                    mappings:
                        name: { boost: 50, analyzer: snowball }
                        description: ~
                        brandName: { boost: 25 }
                        categoryName: { boost: 25 }
                        added: ~
                        area: ~
                    persistence:
                        driver: orm
                        model: ThreadAndMirror\ProductsBundle\Entity\Product
                        finder: ~
                        provider: ~
                        listener:
                            immediate: ~
                        repository: ThreadAndMirror\ProductsBundle\Repository\ProductFinderRepository

# Snc Redis
snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: %redis_dsn%
        session:
            type: phpredis
            alias: session
            dsn: %redis_dsn%
        doctrine:
            type: phpredis
            alias: doctrine
            dsn: %redis_dsn%
    session:
        client: session
        prefix: session:main
        use_as_default: true
    doctrine:
        metadata_cache:
            client: doctrine
            entity_manager: default          # the name of your entity_manager connection
            document_manager: default        # the name of your document_manager connection
        result_cache:
            client: doctrine
            entity_manager: [default, read]  # you may specify multiple entity_managers
        query_cache:
            client: doctrine
            entity_manager: default

# Buzz config
sensio_buzz:
    client_timeout: 30

# Liip Imagine
liip_imagine:
    resolvers:
       default:
          web_path: ~
    filter_sets:
        cache: ~
        page_banner:
            quality: 50
            filters:
                thumbnail: { size: [1280, 400], mode: outbound }
        blog_header:
            quality: 80
            filters:
                thumbnail: { size: [1080, 720], mode: outbound }
        blog_homepage_main:
            quality: 80
            filters:
                thumbnail: { size: [960, 450], mode: outbound }
        blog_homepage_circle:
            quality: 80
            filters:
                thumbnail: { size: [240, 240], mode: outbound }

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    node: /usr/local/bin/node
    assets:
        admin_js:
            inputs:
                - '@StemsCoreBundle/Resources/public/js/admin/vendor/*'
                - '@StemsCoreBundle/Resources/public/js/admin/admin.js'
                - '@StemsPageBundle/Resources/public/js/admin.js'
                - '@StemsMediaBundle/Resources/public/js/admin.js'
                - '@StemsBlogBundle/Resources/public/js/admin/admin.js'
                - '@ThreadAndMirrorEditorsPicksBundle/Resources/public/js/admin.js'
                - '@ThreadAndMirrorProductsBundle/Resources/public/js/admin.js'
        admin_css:
            inputs:
                - '@StemsCoreBundle/Resources/public/css/admin/vendor/*'
                - '@StemsCoreBundle/Resources/public/css/admin/admin.css'
                # - '@StemsBlogBundle/Resources/public/css/admin/stylesheet.less'
        frontend_vendor_js:
            inputs:
                - '@StemsCoreBundle/Resources/public/js/front/vendor/*'
        frontend_js:
            inputs:
                - '@ThreadAndMirrorSocialBundle/Resources/public/js/frontend.js'
                - '@StemsCoreBundle/Resources/public/js/front/frontend.js'
        frontend_css:
            inputs:
                - '@StemsCoreBundle/Resources/public/css/front/vendor/*'
                - '@ThreadAndMirrorProductsBundle/Resources/public/css/stylesheet.css'
    filters:
        cssrewrite: ~
        less: ~
        uglifycss:
            bin: /usr/local/bin/uglifycss
        uglifyjs2:
            bin: /usr/local/bin/uglifyjs

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        metadata_cache_driver: redis
        query_cache_driver: redis

stof_doctrine_extensions:
    orm:
        default:
            sluggable: true

# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    host:       %mailer_host%
    auth_mode:  %mailer_auth_mode%
    username:   %mailer_user%
    password:   %mailer_password%

# NewRelic Configuration
ekino_new_relic:
    enabled: true                         # Defaults to true
    application_name: 'Thread and Mirror' # default value in newrelic is "PHP Application", or whatever is set
                                          # as php ini-value
    api_key: e7f98a1be3616d3aee990c449b1c79b327904381b7276b4
    license_key: d8da1bf508edbecfa229f05f00edb7428b7276b4
    xmit: false                           # if you want to record the metric data up to the point newrelic_set_appname is called, set this to true
    logging: false                        # If true, logs all New Relic interactions to the Symfony log
    instrument: false                     # If true, uses enhanced New Relic RUM instrumentation (see below)
    log_exceptions: true                  # If true, sends exceptions to New Relic
    log_commands: true                    # If true, logs CLI commands to New Relic as Background jobs (>2.3 only)
    using_symfony_cache: false            # Symfony HTTP cache (see below)
    transaction_naming: route             # route, controller or service (see below)
    transaction_naming_service: ~         # Transaction naming service (see below)
    ignored_routes: []                    # No transaction recorded for this routes
    ignored_paths: []                     # No transaction recorded for this paths
    ignored_commands: []                  # No transaction recorded for this commands (background tasks)

# Global Params (Override Bundle Defaults)
parameters:
    stems.site.theme: 'threadandmirror'
    stems.site.name: 'Thread & Mirror'
    stems.site.url: 'http://www.threadandmirror.com'
    stems.site.description: 'All Luxury, One Site: Fashion, Beauty, Blog, Street Chic, The Social Circle and Sale Alerts'
    stems.site.email: 'info@threadandmirror.com'
    stems.site.keywords: 'Fashion, Street Chic, Style, Clothing, Sales, Beauty, Blog, Style Exchange, Sale Alerts, Shop, Offer, High Fashion, Fashion Shows, Sample Sale, Sample Sales, Luxury'
    stems.media.image.categories: 
        general: 'General'
        blog:    'Blog'
    stems.sections.available:
        page:
            magazine:
                name: 'Magazine'
                enabled: true
                entity: 'StemsPageBundle:SectionMagazine'
                class: 'Stems\PageBundle\Entity\SectionMagazine'
                form: 'Stems\PageBundle\Form\SectionMagazineType'
            text:
                name: 'Text'
                enabled: true
                entity: 'StemsPageBundle:SectionText'
                class: 'Stems\PageBundle\Entity\SectionText'
                form: 'Stems\PageBundle\Form\SectionTextType'
            heading:
                name: 'Heading'
                enabled: true
                entity: 'StemsPageBundle:SectionHeading'
                class: 'Stems\PageBundle\Entity\SectionHeading'
                form: 'Stems\PageBundle\Form\SectionHeadingType'
            text_and_image:
                name: 'Text and Image'
                enabled: true
                entity: 'StemsPageBundle:SectionTextAndImage'
                class: 'Stems\PageBundle\Entity\SectionTextAndImage'
                form: 'Stems\PageBundle\Form\SectionTextAndImageType'
            image:
                name: 'Image'
                enabled: true
                entity: 'StemsPageBundle:SectionImage'
                class: 'Stems\PageBundle\Entity\SectionImage'
                form: 'Stems\PageBundle\Form\SectionImageType'
            poll:
                name: 'Poll'
                enabled: true
                entity: 'StemsPollBundle:SectionPoll'
                class: 'Stems\PollBundle\Entity\SectionPoll'
                form: 'Stems\PollBundle\Form\SectionPollType'
            product_gallery:
                name: 'Product Gallery'
                enabled: true
                entity: 'ThreadAndMirrorProductsBundle:SectionProductGallery'
                class: 'ThreadAndMirror\ProductsBundle\Entity\SectionProductGallery'
                form: 'ThreadAndMirror\ProductsBundle\Form\SectionProductGalleryType'
        blog:
            text:
                name: 'Text'
                enabled: true
                entity: 'StemsPageBundle:SectionText'
                class: 'Stems\PageBundle\Entity\SectionText'
                form: 'Stems\PageBundle\Form\SectionTextType'
            heading:
                name: 'Heading'
                enabled: true
                entity: 'StemsPageBundle:SectionHeading'
                class: 'Stems\PageBundle\Entity\SectionHeading'
                form: 'Stems\PageBundle\Form\SectionHeadingType'
            list:
                name: 'List'
                enabled: true
                entity: 'StemsPageBundle:SectionList'
                class: 'Stems\PageBundle\Entity\SectionList'
                form: 'Stems\PageBundle\Form\SectionListType'
            image:
                name: 'Image'
                enabled: true
                entity: 'StemsPageBundle:SectionImage'
                class: 'Stems\PageBundle\Entity\SectionImage'
                form: 'Stems\PageBundle\Form\SectionImageType'
            poll:
                name: 'Poll'
                enabled: true
                entity: 'StemsPollBundle:SectionPoll'
                class: 'Stems\PollBundle\Entity\SectionPoll'
                form: 'Stems\PollBundle\Form\SectionPollType'
            product_gallery:
                name: 'Product Gallery'
                enabled: true
                entity: 'ThreadAndMirrorProductsBundle:SectionProductGallery'
                class: 'ThreadAndMirror\ProductsBundle\Entity\SectionProductGallery'
                form: 'ThreadAndMirror\ProductsBundle\Form\SectionProductGalleryType'

# Global Services
services:
    threadandmirror.logger:
        class: Symfony\Bridge\Monolog\Logger

    threadandmirror.product.parser:
        class: ThreadAndMirror\ProductsBundle\Service\ProductParser
        arguments: 
            em: "@doctrine.orm.entity_manager"

    threadandmirror.linkshare:
        class: ThreadAndMirror\ProductsBundle\Service\Linkshare
        arguments: 
            em: "@doctrine.orm.entity_manager"
            ProductParser: "@threadandmirror.product.parser"

    threadandmirror.product.filter:
        class: ThreadAndMirror\ProductsBundle\Service\ProductFilter
        arguments: 
            em: "@doctrine.orm.entity_manager"
            services:

    # KernelRequest listener
    # extension.listener:
    #     class: Acme\DemoBundle\Listener\DoctrineExtensionListener
    #     calls:
    #         - [ setContainer, [ @service_container ] ]
    #     tags:
    #         # translatable sets locale after router processing
    #         - { name: kernel.event_listener, event: kernel.request, method: onLateKernelRequest, priority: -10 }
    #         # loggable hooks user username if one is in security context
    #         - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # Doctrine Extension listeners to handle behaviors
    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
            - [ setDefaultLocale, [ %locale% ] ]
            - [ setTranslationFallback, [ false ] ]

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.loggable:
        class: Gedmo\Loggable\LoggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

# Logging
monolog:
    handlers:
        main:
            type: stream
            path: %kernel.root_dir%/%kernel.environment%.log
            level: error
        threadandmirror:
            type: stream
            path: %kernel.root_dir%/logs/threadandmirror.log
            level: warning
        crawler:
            type: stream
            path: %kernel.root_dir%/logs/crawler.log
            level: warning