thread_and_mirror_blog:
    resource: "@ThreadAndMirrorBlogBundle/Resources/config/routing.yml"
    prefix:   /

thread_core:
    resource: "@ThreadAndMirrorCoreBundle/Resources/config/routing.yml"
    prefix:   /

stems_poll:
    resource: "@StemsPollBundle/Resources/config/routing.yml"
    prefix:   /

thread_streetchic:
    resource: "@ThreadAndMirrorStreetChicBundle/Resources/config/routing.yml"
    prefix:   /

thread_moodboard:
    resource: "@ThreadAndMirrorMoodBoardBundle/Resources/config/routing.yml"
    prefix:   /

stems_social:
    resource: "@StemsSocialBundle/Resources/config/routing.yml"
    prefix:   /

thread_social:
    resource: "@ThreadAndMirrorSocialBundle/Resources/config/routing.yml"
    prefix:   /

thread_alert:
    resource: "@ThreadAndMirrorAlertBundle/Resources/config/routing.yml"
    prefix:   /

thread_editorspicks:
    resource: "@ThreadAndMirrorEditorsPicksBundle/Resources/config/routing.yml"
    prefix:   /

stems_media:
    resource: "@StemsMediaBundle/Resources/config/routing.yml"
    prefix:   /

stems_core:
    resource: "@StemsCoreBundle/Resources/config/routing.yml"
    prefix:   /

thread_products:
    resource: "@ThreadAndMirrorProductsBundle/Resources/config/routing.yml"
    prefix:   /

ThreadAndMirrorBlogBundle:
    resource: "@ThreadAndMirrorBlogBundle/Resources/config/routing.yml"
    prefix:   /

StemsUserBundle:
    resource: "@StemsUserBundle/Resources/config/routing.yml"
    prefix:   /

StemsPageBundle:
    resource: "@StemsPageBundle/Resources/config/routing.yml"
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"