services:

    threadandmirror.blog.repository.section:
        class:           ThreadAndMirror\BlogBundle\Repository\SectionRepository
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments:
            - ThreadAndMirror\BlogBundle\Entity\Section

    threadandmirror.product.parser:
        class: ThreadAndMirror\ProductsBundle\Service\ProductParser
        arguments:
            em: "@doctrine.orm.entity_manager"

    threadandmirror.linkshare:
        class: ThreadAndMirror\ProductsBundle\Service\Linkshare
        arguments:
            em: "@doctrine.orm.entity_manager"
            ProductParser: "@threadandmirror.product.parser"

    threadandmirror.product.filter:
        class: ThreadAndMirror\ProductsBundle\Service\ProductFilter
        arguments:
            em: "@doctrine.orm.entity_manager"

    # Doctrine Extension listeners to handle behaviors
    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
            - [ setDefaultLocale, [ %locale% ] ]
            - [ setTranslationFallback, [ false ] ]

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.loggable:
        class: Gedmo\Loggable\LoggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    redis.service:
        class: Redis
        calls:
            - [connect, [localhost, 6379]]

    doctrine.cache.redis:
        class: Doctrine\Common\Cache\RedisCache
        calls:
            - [setRedis, [@redis.service]]