thread_editorspicks_admin:
    resource: "@ThreadAndMirrorEditorsPicksBundle/Controller/AdminController.php"
    type:     annotation

thread_editorspicks_front:
    resource: "@ThreadAndMirrorEditorsPicksBundle/Controller/FrontController.php"
    type:     annotation

thread_editorspicks_popup:
    resource: "@ThreadAndMirrorEditorsPicksBundle/Controller/PopupController.php"
    type:     annotation

thread_editorspicks_rest:
    resource: "@ThreadAndMirrorEditorsPicksBundle/Controller/RestController.php"
    type:     annotation