### ADMIN ROUTES ####################################################

stems_admin_core_developer_generate_product_sitemaps:
    pattern:  /admin/developer/sitemap/products
    defaults: { _controller: ThreadAndMirrorProductsBundle:Admin:productSitemaps }




thread_products_front:
    resource: "@ThreadAndMirrorProductsBundle/Controller/FrontController.php"
    type:     annotation

thread_products_rest:
    resource: "@ThreadAndMirrorProductsBundle/Controller/RestController.php"
    type:     annotation


### DATA ROUTES ####################################################

thread_products_data_update_new_products:
    pattern:  /operations/update-new-products/{type}/{shop}
    defaults: { _controller: ThreadAndMirrorProductsBundle:Data:updateNewProducts }

thread_products_data_update_wishlist_alerts:
    pattern:  /operations/update-wishlist-alerts/
    defaults: { _controller: ThreadAndMirrorProductsBundle:Data:updateWishlistAlerts }

thread_products_data_cleanup_latest_additions:
    pattern:  /operations/cleanup-latest-additions/
    defaults: { _controller: ThreadAndMirrorProductsBundle:Data:cleanupLatestAdditions }

thread_products_data_check_single_products:
    pattern:  /operations/check-single-products/{limit}/{offset}
    defaults: { _controller: ThreadAndMirrorProductsBundle:Data:checkSingleProducts }

thread_products_data_cleanup_duplicate_products:
    pattern:  /operations/cleanup-duplicate-products/{limit}
    defaults: { _controller: ThreadAndMirrorProductsBundle:Data:cleanupDuplicateProducts }

### REST ROUTES ####################################################

thread_products_rest_add_to_wishlist:
    pattern:  /rest/add-to-wishlist/{id}
    defaults: { _controller: ThreadAndMirrorProductsBundle:Rest:addToWishlist }

thread_products_rest_remove_from_wishlist:
    pattern:  /rest/remove-from-wishlist/{id}
    defaults: { _controller: ThreadAndMirrorProductsBundle:Rest:removeFromWishlist }

thread_products_rest_save_favourite_filters:
    pattern:  /rest/save-favourite-filters
    defaults: { _controller: ThreadAndMirrorProductsBundle:Rest:saveFavouriteFilters }

thread_products_rest_add_product_from_url:
    pattern:  /rest/add-product-from-url
    defaults: { _controller: ThreadAndMirrorProductsBundle:Rest:addProductFromUrl }

thread_products_rest_add_to_outfit:
    pattern:  /rest/add-to-outfit/{id}/{outfit}
    defaults: { _controller: ThreadAndMirrorProductsBundle:Rest:addToOutfit }

thread_products_rest_set_outfit_featured:
    pattern:  /rest/set-outfit-featured/{id}
    defaults: { _controller: ThreadAndMirrorProductsBundle:Rest:setOutfitFeatured }

thread_products_rest_view_product:
    pattern:  /rest/view-product/{id}
    defaults: { _controller: ThreadAndMirrorProductsBundle:Rest:viewProduct }

thread_products_rest_add_new_outfit:
    pattern:  /rest/add-new-outfit
    defaults: { _controller: ThreadAndMirrorProductsBundle:Rest:addNewOutfit }

thread_products_rest_parse_productgalleryproduct:
    pattern:  /admin/products/rest/parse-product-gallery-product/{id}
    defaults: { _controller: ThreadAndMirrorProductsBundle:Rest:parseProductGalleryProduct }

